### ISSUE TITLE
Admin refactor

### ISSUE THREAD

**Issue by jeffnb** [cesarmarroquin/demo_project#1]
class TeacherAdmin(UserAdmin):
    pass
admin.site.register(Teacher, TeacherAdmin)

The class TeacherAdmin is not needed.  Please refactor to simply use the model unless you are going to add functionality to the TeacherAdmin

**Comment by cesarmarroquin** [comment]
I actually had to add functionality to that model and extra fields that I needed a teacher to have. The only field I needed to add was a profile picture.
